### PR TITLE
Fix fork

### PR DESCRIPTION
**Pull request by sumamu**
Waiting for more confirmations of successful resync from scratch.

### CODE REVIEW

**Review by 0x3639 — APPROVED** [review]
I've tested this on 5 different nodes with sync from bootstrap after the fork.  All were successful.  Other have tested from scratch and different bootstrap from before the fork.  All were successful.

**Comment by georgezgeorgez** [comment]
I have yet to test this myself with a resync. 

I know I suggested stable sort as an option, but any particular reason why it was chosen over falling back to hashes in the case of time stamp collision?

Was it the fact that the sort stable "just worked" with the live chain?

Or did the the hash-based comparison fail to produce the live chain?

Just curious.

**Comment by georgezgeorgez** [comment]
Also can we squash these commits?

**Comment by georgezgeorgez** [comment]
After we fix this issue, we should proactively search the codebase for other sorts and see if it's a possible issue elsewhere.

**Comment by sumamu** [comment]
> Was it the fact that the sort stable "just worked" with the live chain?
Fortunately, it did and this solution was more elegant than comparing hashes.

> Or did the the hash-based comparison fail to produce the live chain?
I didn't test this in the end. The other solution seemed better and it produced the expected results.

> The solution we choose is restricted by the need to produce the results that are already on chain.
There were 2 forks:
- one without any downtime
- the other with ~2  hours of downtime after the fork momentum.

We could've chosen any, but it seemed natural to choose the one without downtime because in the end it was the longer chain.

**Comment by sumamu** [comment]
You're right to make this clear for future reference. 
I do remember there are other places in the go-zenon code where leveldb's lexicographical ordering is relied upon.

**Review by MoonBaZZe — APPROVED** [review]

**Review by georgezgeorgez — APPROVED** [review]
lgtm

**Pull request merged**
