### PR TITLE
[fmt] Omit comparison with boolean constant and fmt imports

### PR DESCRIPTION
**Pull request by georgezgeorgez**
https://staticcheck.dev/docs/checks/#S1002

### CODE REVIEW

**Review by 0x3639 — APPROVED** [review]

**Comment by georgezgeorgez** [comment]
to squash

**Comment by MoonBaZZe** [comment]
Why did you have to do this change?

**Comment by MoonBaZZe** [comment]
I suggest you do a full resync to test changes like this. I will approve after you tell me everything is ok

**Comment by georgezgeorgez** [comment]
> Why did you have to do this change?

In terms of S1002 specifically, it's more idiomatic and less verbose.
Overall, static analysis is a useful tool if you are diligent about addressing it.
Always good to run checks on new code, but in order to get there need to maintain the old code to reduce noise.

> I suggest you do a full resync to test changes like this. I will approve after you tell me everything is ok

This is pretty much just a formatting change. The logic is the exact same.
It's possible I made an error, but that can be detected with review.

**Review by MoonBaZZe — APPROVED** [review]

**Review by sumamu — APPROVED** [review]

**Comment by georgezgeorgez** [comment]
squashing

**Pull request merged**
