### PR TITLE
[rpc] Fix BalanceInfo UnmarshalJSON

### PR DESCRIPTION
**Pull request by georgezgeorgez**
Surprised that no one else ran into this issue yet...

### CODE REVIEW

**Comment by georgezgeorgez** [comment]
I'm running into errors related to unmarshalling BalanceInfo
Need to do some testing

**Comment by georgezgeorgez** [comment]
I guess most clients are Dart (syrius) so aren't using these unmarshal methods

**Comment by georgezgeorgez** [comment]
For AccountBlock, what is this check for?
`if block.TokenInfo != nil {`
in
```
func (block *AccountBlock) UnmarshalJSON(data []byte) error {
	aux := new(AccountBlockMarshal)
	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	block.AccountBlock = *aux.FromNomMarshalJson()
	if block.TokenInfo != nil {
		block.TokenInfo = aux.TokenInfo.FromTokenMarshal()
	}
	block.ConfirmationDetail = aux.ConfirmationDetail
	if block.PairedAccountBlock != nil {
		block.PairedAccountBlock = aux.PairedAccountBlock.FromApiMarshalJson()
	}
	return nil
}
```

Is this checking the transaction is using the zero/empty token?
Wouldn't you check the aux then?
i.e `if aux.TokenInfo != nil {`

Making sure I don't need to do the same kind of check for BalanceInfo

**Comment by georgezgeorgez** [comment]
My testing has confirmed this change works as intended

**Comment by georgezgeorgez** [comment]
And I think I can confirm AccountBlock Unmarshal is not working properly also. I will create a separate PR for that.

**Comment by Sol-Sanctum** [comment]
@sumamu @MoonBaZZe Can you please check this out?

**Review by MoonBaZZe — COMMENTED** [review]
Seems good!

**Review by MoonBaZZe — APPROVED** [review]
Seems good!

**Review by sumamu — APPROVED** [review]

**Review by 0x3639 — APPROVED** [review]

**Comment by 0x3639** [comment]
I've this question before, and someone indicated we should wait for the requestor to merge them.  So I was hoping George would do that.

**Pull request merged**
