### PR TITLE
[p2p] Allow discovery refresh to handle empty peers

### PR DESCRIPTION
**Pull request by georgezgeorgez**

### CODE REVIEW

**Comment by georgezgeorgez** [comment]
This change is useful for single node testnets

**Comment by georgezgeorgez** [comment]
Not sure if there are any stated assumptions about nonzero seeder length, but I will label this as a bug.
Either assert nonzero length, or check the length between doing arithmetic and logic on it.

**Review by MoonBaZZe — APPROVED** [review]
Nasty bug

**Comment by 0x3639** [comment]
@georgezgeorgez how did you discover this bug?  Is this related to the slow sync after fork, or discovery in setting up an single node testnet?

**Review by 0x3639 — APPROVED** [review]

**Comment by georgezgeorgez** [comment]
@0x3639 discovery in single node testnet
it would always crash after height 180
or after 30 minutes which is the frequency of the discovery refresh

**Review by sumamu — APPROVED** [review]

**Pull request merged**
